import { ColorHelper } from '../../../helpers';
import { OPACITY_LEVEL } from '../opacity/opacity';
import { BASE_COLOR } from './base_color';

export const CONTEXTUAL_COLORS = {
  CONTENT: {
    BRAND: BASE_COLOR.PRIMARY[500],
    TITLE: BASE_COLOR.NEUTRAL[1000],
    BASE: ColorHelper.hexToRGB(
      BASE_COLOR.NEUTRAL[1000],
      OPACITY_LEVEL.SEMIOPAQUE
    ),
    PLACEHOLDER: ColorHelper.hexToRGB(
      BASE_COLOR.NEUTRAL[1000],
      OPACITY_LEVEL.DEEP
    ),
  },
  LAYOUT: {
    BRAND: BASE_COLOR.PRIMARY[500],
    BODY: BASE_COLOR.NEUTRAL[300],
    SURFACE: BASE_COLOR.NEUTRAL[100],
    SPOTLIGHT: BASE_COLOR.NEUTRAL[100],
  },
  INTERACTIVE: {
    PRIMARY: BASE_COLOR.PRIMARY[500],
    PRIMARY_HOVER: BASE_COLOR.PRIMARY[400],
    SECONDARY: ColorHelper.hexToRGB(
      BASE_COLOR.NEUTRAL[1000],
      OPACITY_LEVEL.SEMITRANSPARENT
    ),
    SECONDARY_HOVER: ColorHelper.hexToRGB(
      BASE_COLOR.NEUTRAL[1000],
      OPACITY_LEVEL.LIGHT
    ),
    DESTRUCTIVE: BASE_COLOR.DANGER[500],
    DESTRUCTIVE_HOVER: BASE_COLOR.DANGER[400],
  },
  HIGHTLIGHT: {
    FOCUS: BASE_COLOR.PRIMARY[500],
    PROMOTE: BASE_COLOR.ACCENT[500],
  },
};
