import { BASE_COLOR } from './base_color';

export const SEMANTIC_COLORS = {
  PRIMARY: {
    PURE: BASE_COLOR.PRIMARY[500],
    LIGHT: BASE_COLOR.PRIMARY[200],
    MID: BASE_COLOR.PRIMARY[400],
    DARK: BASE_COLOR.PRIMARY[900],
  },
  ACCENT: {
    PURE: BASE_COLOR.ACCENT[500],
    LIGHT: BASE_COLOR.ACCENT[100],
    MID: BASE_COLOR.ACCENT[400],
    DARK: BASE_COLOR.ACCENT[900],
  },
  NEUTRAL: {
    WHITE: BASE_COLOR.NEUTRAL[100],
    BLACK: BASE_COLOR.NEUTRAL[1000],
  },
  LOW: {
    PURE: BASE_COLOR.NEUTRAL[700],
    LIGHT: BASE_COLOR.NEUTRAL[800],
    MID: BASE_COLOR.NEUTRAL[900],
  },
  HIGH: {
    PURE: BASE_COLOR.NEUTRAL[400],
    LIGHT: BASE_COLOR.NEUTRAL[300],
    MID: BASE_COLOR.NEUTRAL[200],
  },
  SUCCESS: {
    PURE: BASE_COLOR.SUCCESS[500],
    LIGHT: BASE_COLOR.SUCCESS[200],
    MID: BASE_COLOR.SUCCESS[400],
    DARK: BASE_COLOR.SUCCESS[900],
  },
  WARNING: {
    PURE: BASE_COLOR.WARNING[500],
    LIGHT: BASE_COLOR.WARNING[200],
    MID: BASE_COLOR.WARNING[400],
    DARK: BASE_COLOR.WARNING[900],
  },
  DANGER: {
    PURE: BASE_COLOR.DANGER[500],
    LIGHT: BASE_COLOR.DANGER[200],
    MID: BASE_COLOR.DANGER[400],
    DARK: BASE_COLOR.DANGER[900],
  },
};
